### ISSUE TITLE
Clarity on parameters

### ISSUE THREAD

**Issue by SamHodgs122** [wal-yan/bed-filter#1]
Hi, 

What is the parameters for publishDir and bedfile reference?

Thanks in advance,
Sam

**Comment by abhi18av** [comment]
Hey @SamHodgs122 , the parameter for publishDir is `--publish_dir_mode`

I suggest you use it as shown `nextflow run ... --publish_dir_mode copy` so that the results get copied over to the output directory.

For the bed file reference, you can use `--bed /path/to/example.bed` 

Reference https://github.com/wal-yan/bed-filter/blob/a3ac7a61302d9b544bac2e6612d96b00d183c80c/main.nf#L26C37-L26C47

**Comment by SamHodgs122** [comment]
Thanks!

**Comment by abhi18av** [comment]
You're welcome @SamHodgs122 !

@t4ly4 , could you please update the documentation for this project as well?

Three key points we need to highlight
- Objective
- Samplesheet
- Parameters
